import timeout from "./first.js";
import addIcons from "./icons.js";
import cursorPosition from "./cursor.js";
import playOnHover from "./playOnHover.js";
import burgerMenu from "./burgerMenu.js";
cursorPosition();
timeout();
addIcons();
playOnHover();
burgerMenu();
